### ISSUE TITLE
Rollback command on specific player

### ISSUE THREAD

**Issue by vurden** [WINGS7N/JDLogger#10]
I'm not sure if you even take issues, but I figured I would at least give it a shot. I might be missing something, I couldn't find any docs on this plugin, but there doesn't seem to be a way to actually rollback the player's inventory who died. Instead, when I run the command, it sets my inventory to their rollback inventory. I would like to be able to just run the command and reset said player's inventory.

**Comment by WINGS7N** [comment]
Thanks for your suggestion/bug report. I think it's a good idea to add both commands, for example: ```
/jdl r <args>
``` for rollback to player's inventory and something like ```
/jdl r <args> --to-my (-m)
```
